# Generated by Django 3.2 on 2022-09-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='media')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movies', to='category.category')),
            ],
        ),
    ]
