# Generated by Django 3.2 on 2022-09-06 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0001_initial'),
        ('comments_and_likes', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('movie', 'user')},
        ),
    ]
